baseurl = "https://b5y.github.io/"
languageCode = "en-US"
title = "Mehti Musayev"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.jpeg"
  author = "Mehti Musayev"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "b5y"
  Email         = "mehty.musaev@gmail.com"
  Twitter       = "b4ym"
  LinkedIn      = "mehtimusayev"
  Stackoverflow = ""
  Medium        = ""
  Telegram      = "me_mu"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
